FROM python_base:latest
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
ENV DEBIAN_FRONTEND=noninteractive
ARG USER_ID=1000
ARG GROUP_ID=1000
# Set up locale and install curl
USER root
RUN apt-get update && \
  apt-get install -y locales curl && \
  locale-gen en_US.UTF-8 && \
  update-locale LANG=en_US.UTF-8

# Set environment variables
ENV LANG=en_US.UTF-8 \
  LANGUAGE=en_US:en \
  LC_ALL=en_US.UTF-8 \
  TERM=alacritty

# install dependencies and temporarily add r-repo
RUN curl -fsSL https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc &&\
  echo "deb https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/" >> /etc/apt/sources.list &&\
  apt-get update && apt-get install -y \
  r-base git fzf ripgrep build-essential fd-find software-properties-common \
  zsh wget unzip luarocks \
  && apt-get clean && rm -rf /var/lib/apt/lists/* && sed -i '$d' /etc/apt/sources.list 

#install node
RUN curl -LO https://nodejs.org/dist/v22.16.0/node-v22.16.0-linux-x64.tar.xz && \
  tar xf node-v22.16.0-linux-x64.tar.xz -C /opt/ && \
  ln -s /opt/node-v22.16.0-linux-x64/bin/* /usr/local/bin/ && \
  npm config set prefix /usr/local/ && \
  npm install -g @anthropic-ai/claude-code mcp-hub @openai/codex


# install lazygit
RUN LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | \
  grep -Po '"tag_name": *"v\K[^"]*') && \
  curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/download/v${LAZYGIT_VERSION}/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz" && \
  tar xf lazygit.tar.gz lazygit && \
  install lazygit -D -t /usr/local/bin/

# install neovim
RUN curl -LO https://github.com/neovim/neovim/releases/download/v0.11.2/nvim-linux-x86_64.tar.gz && \
  tar xzf nvim-linux-x86_64.tar.gz -C /opt && \
  ln -s /opt/nvim-linux-x86_64/bin/nvim /usr/local/bin/nvim 

USER user

# setup neovim config
RUN uv python install 3.12 && uv venv --python 3.12 
ENV VIRTUAL_ENV="/home/user/.venv"
ENV PATH="/home/user/.local/bin:$VIRTUAL_ENV/bin:$PATH"

RUN uv tool install 'vectorcode[lsp,mcp]' \
  && git clone https://github.com/vyakimov/neovim_setup.git ~/.config/nvim && \
  nvim --headless "+Lazy! sync" +qa \
  && uv pip install --upgrade --no-cache-dir ipython pyright

COPY --chown=user:user bootstrap.sh /home/user/bootstrap.sh
COPY --chown=user:user gitstatusd-linux-x86_64 /home/user/.cache/gitstatus/gitstatusd-linux-x86_64

RUN chmod +x /home/user/bootstrap.sh && \
  chmod +x /home/user/.cache/gitstatus/gitstatusd-linux-x86_64 && \
  /home/user/bootstrap.sh && \
  curl -sSL https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info | tic -x -

WORKDIR /app

