nvim --headless "+MasonInstall r-languageserver" +q! &&
  nvim --headless "+MasonInstall black" +q! &&
  nvim --headless "+MasonInstall docker-compose-language-service" +q! &&
  nvim --headless "+MasonInstall docker-language-server" +q! &&
  nvim --headless "+MasonInstall hadolint" +q! &&
  nvim --headless "+MasonInstall json-lsp" +q! &&
  nvim --headless "+MasonInstall lua-language-server" +q! &&
  nvim --headless "+MasonInstall markdown-toc" +q! &&
  nvim --headless "+MasonInstall markdownlint-cli2" +q! &&
  nvim --headless "+MasonInstall marksman" +q! &&
  nvim --headless "+MasonInstall mypy" +q! &&
  nvim --headless "+MasonInstall prettierd" +q! &&
  nvim --headless "+MasonInstall pyright" +q! &&
  nvim --headless "+MasonInstall ruff" +q! &&
  nvim --headless "+MasonInstall shellcheck" +q! &&
  nvim --headless "+MasonInstall shfmt" +q! &&
  nvim --headless "+MasonInstall stylua" +q! &&
  nvim --headless "+MasonInstall taplo" +q! &&
  nvim --headless "+MasonInstall yaml-language-server" +q!
